/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-data-jpa:2.4.0")
    implementation("org.springframework.boot:spring-boot-starter-web:2.4.0")
    implementation("javax.validation:validation-api:2.0.1.Final")
    implementation("org.springframework.boot:spring-boot-starter-validation:2.3.2.RELEASE")
    implementation("com.google.code.gson:gson:2.8.5")
    implementation("io.jsonwebtoken:jjwt:0.9.0")
    implementation("org.springframework.boot:spring-boot-starter-security:2.4.0")
    implementation("org.postgresql:postgresql:42.5.0")

    runtimeOnly("org.springframework.boot:spring-boot-devtools:2.4.0")
    runtimeOnly("com.h2database:h2:1.4.200")
    runtimeOnly("mysql:mysql-connector-java:8.0.22")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.4.0")
}

group = "com.lige110.springReact"
version = "0.0.1-SNAPSHOT"
description = "ppmtool"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
