version: '3.7'
services:
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "3678:5432"

  ppmbackend:
    image: ligedocker110/ppmbackend:latest
    restart: always
    environment:
      PQ_URL: database
    ports:
      - "8080:8080"


