apiVersion: v1
kind: Pod
metadata:
  labels:
    run: postgres
  name: backend-db
spec:
  containers:
    - image: postgres
      name: db
      ports:
        - containerPort: 5432
          name: postgres
      env:
      - name: POSTGRES_USER
        valueFrom:
          configMapKeyRef:
            name: db-config
            key: postgres_username
      - name: POSTGRES_PASSWORD
        valueFrom:
          configMapKeyRef:
            name: db-config
            key: postgres_password
#      volumeMounts:
#        - mountPath: /var/lib/postgresql/data
#          name: postgres-pv-claim
#  volumes:
#    - name: postgres-pv-claim
#      persistentVolumeClaim:
#        claimName: postgres-pv-claim
  dnsPolicy: ClusterFirst
  restartPolicy: Always