apiVersion: v1
kind: Pod
metadata:
  labels:
    run: postgres
  name: backend-db
spec:
  containers:
    - image: postgres
      name: db
      ports:
        - containerPort: 5432
          name: postgres
      env:
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        value: postgres
  dnsPolicy: ClusterFirst
  restartPolicy: Always