apiVersion: v1
kind: Service
metadata:
  name: ppmbackend
spec:
  selector:
    run: backend
    app: ppm
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30036